### ISSUE TITLE
Use keep-alive between nginx and upstream servers

### ISSUE THREAD

**Issue by mpnally** [30x/dispatcher#3]
While doing load-testing on OSX, I discovered that, for that OS, it is necessary to turn on keep-alive between nginx and the upstream servers. If you don't, you will see very poor performance and various timeouts and other errors.

Experimenting with load-testing on Linux, it seems that Linux behaves much better than OSX when keep-alive is not used. Basically things run pretty smoothly.

That said, not using keep-alive seems wasteful. It means that every communication between nginx and the upstream servers has to create a new TCP connection. It seems likely that enabling keep-alive would improve performance, possibly significantly. The configuration changes to turn on keep-alive are described in this blog: https://ma.ttias.be/enable-keepalive-connections-in-nginx-upstream-proxy-configurations/

Here is an example from my OSX nginx config:

```
    upstream permissions_maintenance {
        keepalive 100;
        server 127.0.0.1:3001;
    }
...    
        location /permissions {
            proxy_set_header Host            $http_host;
            proxy_pass http://permissions_maintenance;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            }
```

The following lines are all necessary — if you omit any of them, keepalive will not work:
```
        keepalive 100;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
```

**Comment by mpnally** [comment]
I talked to Frank  more about this. Frank confirmed that Edge's nginx routers use keep-alive. He also said that running without keep-alive was probably not a good idea: 

"Without keepalive, every request from nginx to upstream will use a new conection and port. You will run out of ephemeral ports quickly. The default linux ephemeral port range may be wider than osx. Linux may also free up those ephemeral ports quicker once nginx is done using it. The cleanup timeout may be shorter"

**Comment by whitlockjc** [comment]
Any way we can see Frank's configuration for nginx?

**Comment by gbrail** [comment]
Yes -- for internal services -- stuff that is being called from another
service inside our network -- testing with keep-alive is a good choice
because we have a relatively small number of "clients".

The only place where testing with keep-alive explicitly makes sense is when
testing stuff that runs on the edge of the network and is hit directly by
clients on the Internet, like the Nginx stuff.

Also, if you do benchmarks with keep-alive turned off, then first you're
mainly benchmarking the socket handling of the OS and server, and second
you will run in to situations in which you'll need to configure your
benchmark client and OS to handle the large number of sockets. Linux does a
poor job of this out of the box and I don't even know how to configure OS X
to handle it.
